version: 2.1

# orbs:
#   aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package | zip -d myfile.zip /home/circleci/project
      - run:
          name: Test
          command: mvn test
      # - aws-s3/sync:
      #     aws-access-key-id: AWS_ACCESS_KEY_ID
      #     aws-region: AWS_REGION
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #     from: bucket
      #     to: 's3://jiraiya106-terraform-state'
      #     arguments: | # Optional arguments
      #        --acl public-read \
      #        --cache-control "max-age=86400"
      #     overwrite: true
      - store_artifacts:
          path: /home/circleci/project/target/store-webapp.jar
          #destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
  

workflows:
  sample: 
    jobs:
      - build-and-test