version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Zip
          command: |
            mkdir project
            cp appspec.yml ./project/appspec.yml
            cp -R scripts ./project/scripts
            mkdir -p /home/circleci/project/arhiv
            zip -r arhiv/myfile.zip appspec.yml scripts target
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: /home/circleci/project/arhiv
          to: 's3://jiraiya106-terraform-state1/'
  
  


workflows:
  sample: 
    jobs:
      - build-and-test 