version: 2.1

# orbs:
#   aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package | mvn package
      # - aws-s3/sync:
      #     aws-access-key-id: AWS_ACCESS_KEY_ID
      #     aws-region: AWS_REGION
      #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #     from: bucket
      #     to: 's3://jiraiya106-terraform-state'
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
         name: Test
         command: mvn test

workflows:
  sample: 
    jobs:
      - build
      - test