version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Zip
          command: |
            mkdir project
            cp appspec.yml ./project/appspec.yml
            cp -R scripts ./project/scripts
            cp /home/circleci/project/target/store-webapp.jar ./project/store-webapp.jar
            ls /home/circleci/project/target/
            mkdir -p /home/circleci/project/arhiv
            zip -jr arhiv/myfile.zip ./project/
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: /home/circleci/project/arhiv
          to: 's3://jiraiya106-terraform-state/'
  
  


workflows:
  sample: 
    jobs:
      - build-and-test
  # deploy_application:
  #   jobs:
  #     - aws-code-deploy/deploy:
  #         application-name: dev # The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
  #         deployment-group: Deploy-group # The name of a new deployment group for the specified application.
  #         service-role-arn: arn:aws:iam::992002333423:role/codedeploy # The service role for a deployment group.
  #         bundle-bucket: s3://jiraiya106-terraform-state # The s3 bucket where an application revision will be stored.
  #         bundle-key: arn:aws:kms:eu-west-2:992002333423:alias/aws/s3